Make normalize_whitespace usable again
The calls to self.normalize_whitespace fail at the moment
with the error:

  TypeError: normalize_whitespace() takes exactly 1 argument (2 given)

We could just add self as the first argument to
self.normalize_whitespace, but since this method isn't
dependent on self, we might as well make it a static
method.